# Generated by Django 5.2.17 on 2026-08-30 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A human-readable label to identify this key, e.g. its purpose or owner.', max_length=100)),
                ('prefix', models.CharField(db_index=True, editable=False, help_text='Public, non-secret identifier used to look up this key.', max_length=32, unique=True)),
                ('hashed_key', models.CharField(editable=False, help_text='SHA-256 hash of the full secret key. The raw key itself is never stored.', max_length=128)),
                ('scopes', models.JSONField(blank=True, default=list, help_text='Permission scopes granted to this key, e.g. ["orders:read", "orders:write"]. Use ["*"] to grant every scope.')),
                ('is_active', models.BooleanField(default=True, help_text='Unchecking this immediately revokes the key without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration timestamp. Leave blank for a key that never expires.', null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
