# Generated by Django 5.2.17 on 2026-08-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationapikey',
            name='last_used_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When this key last authenticated a request. Updated by record_usage().', null=True),
        ),
    ]
