# Generated by Django 5.2.17 on 2026-09-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organizationapikey_last_used_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationapikey',
            name='revoked_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When this key was revoked, if it has been. Set by revoke().', null=True),
        ),
        migrations.AddField(
            model_name='organizationapikey',
            name='revoked_reason',
            field=models.CharField(blank=True, default='', editable=False, help_text='Why this key was revoked, if a reason was given to revoke().', max_length=255),
        ),
    ]
