# Generated by Django 6.1.1 on 2026-09-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationapikey_revoked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationapikey',
            name='allowed_ips',
            field=models.JSONField(blank=True, default=list, help_text='IPs and/or CIDR networks this key may be used from, e.g. ["203.0.113.10", "203.0.113.0/24"]. Leave blank to allow any IP.'),
        ),
        migrations.AddField(
            model_name='organizationapikey',
            name='environment',
            field=models.CharField(choices=[('production', 'Production'), ('staging', 'Staging'), ('development', 'Development'), ('test', 'Test')], default='production', help_text="What this key is meant to be used against. Authoritative -- unlike the _live_/_test_ segment in the key's prefix, this is what application code should actually check.", max_length=20),
        ),
        migrations.AddField(
            model_name='organizationapikey',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Arbitrary application-defined data attached to this key, e.g. {"service": "billing", "owner": "payments-team"}. Not interpreted by this library.'),
        ),
        migrations.AddField(
            model_name='organizationapikey',
            name='rate_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum requests this key may make per rate_limit_window. Leave blank for no rate limiting.', null=True),
        ),
        migrations.AddField(
            model_name='organizationapikey',
            name='rate_limit_window',
            field=models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day')], default='minute', help_text='Window rate_limit is counted over. Ignored unless rate_limit is set.', max_length=10),
        ),
    ]
